### PR TITLE
fix(#1146): update icon button variants

### PR DESCRIPTION
**Pull request by bdfranck**
This PR is for https://github.com/GovAlta/ui-components/issues/1146. It updates the docs to reflect the changes from https://github.com/GovAlta/ui-components/pull/1845. 

The changes include the following:
- Removes `nocolor` variant
- Adds `light` variant
- Adds punctuation and default values to property descriptions

### CODE REVIEW

**Comment by bdfranck** [comment]
This PR is blocked by https://github.com/GovAlta/ui-components/pull/1845. I'll close it until the `icon-button` variant updates are reviewed and merged.

**Comment by bdfranck** [comment]
Instead, I'll re-open it and indicate in the title that it isn't ready for testing.

**Comment by lizhuomeng71** [comment]
Should the Icon Button with light variant be white?

image

**Comment by lizhuomeng71** [comment]
Issue is verified on react and angular, chrome, firefox and edge

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
