### PR TITLE
chore/1801: modal documentation: replacing static modal with button trigger

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
I am using this figma examples, modifying some current examples, replacing static modals with a button, update code. 
https://www.figma.com/design/aeIJGExcpx9ecqnIVwImi1/Component-Pages?node-id=521-254098&t=KvK9Qnow8yOVdavM-4

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
For React, On Another Item Section, onChangeType is not defined, 

Error Message, 
ReferenceError: onChangeType is not defined

image

**Comment by lizhuomeng71** [comment]
This the code example section, the Cancel and exit button should have onClose except of onCancel

image

**Comment by lizhuomeng71** [comment]
For Confirm Record Change for angular
toggleModal not exist
NG9: Property 'toggleModal' does not exist on type 'ModalComponent'.

image

**Comment by lizhuomeng71** [comment]
For angular, add other item, Missing close and Cancel Button

image

**Comment by lizhuomeng71** [comment]
For the Route Change, Both React and Angular are missing the router import

**Comment by lizhuomeng71** [comment]
issue is verified for react and angular.

**Comment by chrisolsen** [comment]
@vanessatran-ddi You will need to fix the commit message :)

**Pull request merged**
