### PR TITLE
fix(#1943): documentation updates filter chip component

### PR DESCRIPTION
**Pull request by syedszeeshan**

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
On Side Nav, Filter Chip should be Filter chip (lower c)
image

Leading Icon is no longer part of this component, therefore Icon Theme property is no longer needed. should be removed

image

**Comment by lizhuomeng71** [comment]
The last example, Typed Chips Example, if I copy the code example, and when I enter an text, the last letter will be omited in the chip

image

**Comment by syedszeeshan** [comment]
> deletable="true" should be a default property goa-filter-chip, and should be a property listed in the properties table

@lizhuomeng71 The deletable property is not exposed in the `GoAFilterChipProps`
Do you still like this property added to the website?

**Comment by syedszeeshan** [comment]
> The last example, Typed Chips Example, if I copy the code example, and when I enter an text, the last letter will be omited in the chip
> 
> image



> On Side Nav, Filter Chip should be Filter chip (lower c) image
> 
> Leading Icon is no longer part of this component, therefore Icon Theme property is no longer needed. should be removed For React leadingicon and icontheme should also be removed image image

@lizhuomeng71 PR has been updated.

**Comment by syedszeeshan** [comment]
> The last example, Typed Chips Example, if I copy the code example, and when I enter an text, the last letter will be omited in the chip
> 
> image

I am looking into this. Will update the PR when ready.

As for the deletable property, as discussed, its not needed.

**Comment by lizhuomeng71** [comment]
For React, If there are Html code and Jsx code, normally it's break into 2 sections, for some of the code snipt, it is not break into 2 sessions

image

**Comment by syedszeeshan** [comment]
> For React Add Random Filter, the function addFilter is not exist
> 
> image

PR updated.

**Comment by lizhuomeng71** [comment]
Issue is verified on react and angular

**Comment by syedszeeshan** [comment]
> Looks good. The one thing that I see that could use a small change is to clean up some of the examples.
> 
> ex image image

I have added margins to the chips and updated the PR. If you need any additional changes, plz let me know.

**Comment by chrisolsen** [comment]
The changes I was after was to make things look good. Part of that was adding some vertical spacing between the chips (no **additional** horizontal), but the other was placing the button and input below the chips so that as new chips are added the button and input aren't moving around. 

For the button example keeping the button centered probably makes sense.

For the input left align the input, as would be seen in a real app.

**Comment by syedszeeshan** [comment]
> The changes I was after was to make things look good. Part of that was adding some vertical spacing between the chips (no **additional** horizontal), but the other was placing the button and input below the chips so that as new chips are added the button and input aren't moving around.
> 
> For the button example keeping the button centered probably makes sense.
> 
> For the input left align the input, as would be seen in a real app.

PR has been updated.

image

image

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
